spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          exception-handling: ignore

    logging:
      level:
        p6spy: info

      decorator:
        datasource:
          p6spy:
            enable-logging: true

